apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vhcy03j08-python 
  janus-idp.io/tekton: vhcy03j08-python
  backstage.io/kubernetes-id: vhcy03j08-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vhcy03j08-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  