apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vhcy03j08-python
  janus-idp.io/tekton: vhcy03j08-python
  backstage.io/kubernetes-id: vhcy03j08-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vhcy03j08-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
