apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vhcy03j08-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vhcy03j08-python 
  name: vhcy03j08-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vhcy03j08-python 
