apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vhcy03j08-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:0895e18a19caa68f30ab052fdbcd3f4ab67f8d5a@sha256:ce137dfe812cc833b9fb95a1011c9ded050de2f1ab4186d94a0db90335dd3956
          name: container-image
